#!/bin/bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
    echo $FILE;
    echo "Running tests..."
    cd "${0%/*}/../../laravel-project"
    vendor/bin/phpunit
    if [ $? -ne 0 ]; then
      echo -e "\e[1;31m\tUnit tests failed ! Aborting commit.\e[0m" >&2
      exit 1;
    fi
fi
done || exit $?
